# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a68019a97386de08f4cd70a83cf0d03b8e28ff48db905eca0be82724e1673b15f3332c499fee35ef9ae8bf75b6e97d1ac1b79b88329f8f6b3ccfa2af7e9dd093

test:
  secret_key_base: 108c002e6f5aee749312b0e293442d5c5610f64469fe2b65bc36b24e9ae211343dacef86501663cbfd06f9b941f92e9f8daffc2bb7c4fefef1973890f3fdda15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
